name: CI Simple

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: use secret
      env : 
        MY_SECRET: ${{secretv2.MY_SUPER_SECRET}}
      run: |
        echo "Le script va utiliser le secret mais ne l'affichera PAS directement."
        if [ -n "$MY_SECRET" ]; then
          echo "Le secret est bien passé en variable d'env !"
        else
          echo "Oops, le secret n'est pas là."
          exit 1
        fi
