name: CI Simple

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: log a text
      run: |  
            echo "line1"
            echo "line2"
            echo "line3"
